### ISSUE TITLE
Changing Highlight Annotation Color Hangs And Fails, Works Fine With Arrows

### ISSUE THREAD

**Issue by turnipsoup** [THeK3nger/obsidian-chessboard#8]
Obsidian Version: v1.6.7

Issue:

The code shows that I can use a specified color for highlight squares or for drawing arrows. When I try to draw arrows in the three colors it works fine. If I try to highlight a square it hangs and fails.

```
fen: r1bqk2r/2p1bppp/p1np1n2/1p2p3/4P3/1B3N2/PPPP1PPP/RNBQR1K1 w kq - 0 8
annotations: Ha4/r         # This fails
annotations: Ab3-d5/r   # This works great
```

I do see that the README states that color customization is a goal still, so maybe this is just not ready yet.

---
Bonus: adding the ability to draw a circle (or another shape) around a square would be nifty!

**Comment by THeK3nger** [comment]
Hello! Colors are still "beta" because I am not in love with the syntax of specifying the colors. In fact, for now, I have some fixed `g`, `r`, `b`, etc colors. But I'd like to have something to specify custom colors (for instance, a particular shade of purple or something like that :D).

Anyway, back to the bug report. I tried this morning and I could not reproduce it. I used this snippet:

````
```chessboard
fen: r1bqk2r/2p1bppp/p1np1n2/1p2p3/4P3/1B3N2/PPPP1PPP/RNBQR1K1 w kq - 0 8
annotations: Ab3-d5/g
annotations: Ha4/g
```
````

And got this image, that looks correct:

![CleanShot 2024-08-15 at 11 02 33@2x](https://github.com/user-attachments/assets/a5db0a5e-c419-493b-acdc-42ad70f4e407)

I am using Obsidian 1.7.0 but I don't think this should be relevant. Any error message in the debug console? (you can open it Ctrl+Alt+I or Cmd+Option+I).

**Comment by turnipsoup** [comment]
Hello!

The the below error using the following codeblock

```
fen: r2qrbk1/1bp2pp1/p2p1n1p/1p6/Pn1PP3/5N1P/1P1N1PP1/RBBQR1K1 b - - 2 17
annotations: Hf5 He5 Hd5 Ae1-e8/g Ab1-h7/g Ad4-d5
annotations: Hf6/g
```

```
Uncaught Error: Input does not look algebraic notation.
    at Chessboard.algebraicToCoord (plugin:obsidian-chessboard:143:19)
    at SVGChessboard.highlight (plugin:obsidian-chessboard:274:34)
    at eval (plugin:obsidian-chessboard:499:32)
    at t.initDOM (app.js:1:1591340)
    at t.toDOM (app.js:1:1160254)
    at t.sync (app.js:1:331424)
    at e.sync (app.js:1:313021)
    at app.js:1:354351
    at e.ignore (app.js:1:434969)
    at t.updateInner (app.js:1:354133)
    at t.update (app.js:1:353888)
    at e.update (app.js:1:443717)
    at e.dispatchTransactions (app.js:1:440278)
    at e.dispatch (app.js:1:442266)
    at app.js:1:1609096
 ```

**Comment by THeK3nger** [comment]
Sorry for the late reply (between my vacation and going back to work at full speed, it has been a busy month).

Anyway, I was not able to replicate the issue. 🤔 From what I see, it is a problem with parsing the annotations, but I thought I already fixed a similar issue.

In any case,  just released version 0.7.0, see if that fixes the issue. If not, I'll dive more into it.
